site_name: Browser
site_author: HENG
site_url:
use_directory_urls: false
nav:
  - 主页: index.md
  - 拓展: extr.md
  - 浏览器架构: stru.md
  - 开发者工具: tools.md
  - 请求: ask.md
  - bug集合: bug.md
  - DNS: dns.md
  - 底层数据包和协议: data.md
  - 网页优化: optimization.md



theme: 
  name: material
  language: zh
  palette:
    scheme: default
    primary: deep orange
  features:
    - content.code.copy
    - content.code.select
  icon:
    repo: fontawesome/brands/github


extra:
  generator: false
  social:
    - icon: fontawesome/brands/pied-piper-alt
      link: http://home.liheng.work/
    - icon: fontawesome/brands/github
      link: https://github.com/lmliheng?tab=repositories

repo_url: https://github.com/lmliheng/codes
repo_name: Heng's Codes

copyright: Copyright 2024 Write By Heng 

markdown_extensions:
  - pymdownx.highlight:

      anchor_linenums: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences   