site_name: git
site_author: HENG
site_url: 
use_directory_urls: false
nav:


     - 主页: index.md
     - 仓库管理: manage.md
     - 连接: connect.md
     - 操作: dev.md
     - 基本流程: flow.md
     - 团队: team.md
     - 脚本: scripts.md


theme: 
  name: material
  language: zh
  palette:
    scheme: default
    primary: deep orange
  features:
    - content.code.copy
    - content.code.select
  icon:
    repo: fontawesome/brands/github
  palette: 


    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: deep orange
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 亮色模式

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: 暗色模式

extra:
  generator: false
  social:
    - icon: fontawesome/brands/pied-piper-alt
      link: http://home.liheng.work/
    - icon: fontawesome/brands/github
      link: https://github.com/lmliheng?tab=repositories

repo_url: https://github.com/lmliheng/codes
repo_name: Heng's Codes

copyright: Copyright 2024 Write By Heng 

markdown_extensions:
  - pymdownx.highlight:

      anchor_linenums: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences  