 site_name: Matlab App Design
 site_author: HENG
 site_url: 
 use_directory_urls: false
 nav:
     - 主页: index.md
     - 应用开发: app_dev.md
     - 组件: assembly.md
     - 回调函数: field.md
     - 登陆界面: login.md
     - 数据分析界面: data.md
     - 应用打包: app_pack.md



 theme: readthedocs