 site_name: SpringBoot
 site_author: HENG
 site_url: 
 use_directory_urls: false
 nav:
     - 主页: index.md
     - 项目构建: build.md
     - 开发笔记: develop.md
     - 注解: release.md
     - 模型: models.md
     - Thymeleaf: thymeleaf.md
     - AOP: aop.md
     - 容器: docker.md
     - 缓存: cache.md
     - 日志: log.md
     - RESTful: restful.md
     - ORM: orm.md
     - 线程池: thread.md
     - 安全框架: security.md
     - 测试: test.md
     - 响应式编程: flux.md
     - 代码片段: code.md
     - 报错: error.md
     
     


 theme: material