site_name: java
site_author: HENG
site_url: 
use_directory_urls: false
nav:
     - 主页: index.md
     - classpath和jar: classpath.md
     - class版本和模块: model.md
     - 基础: base.md
     - 数据类型: data.md
     - 流程控制: flow.md
     - 面向对象: class.md
     - 核心类: mainclass.md
     - 异常处理: excptions.md
     - 集合: collection.md
     - 反射: reflect.md
     - 线程: thread.md
     - 泛型: generic.md
     - 加密: encrypt.md
     - 网络编程: net.md
     - 数据库: db.md
     - web应用部署: web.md
     - 桌面应用: desktop.md
     - 代码: code.md
     - 底层函数: fac.md
     - 使用规范: use.md
     - 常见问题: faq.md



theme: 
  name: material
  language: zh
  palette:
    scheme: default
    primary: deep orange
  features:
    - content.code.copy
    - content.code.select
  icon:
    repo: fontawesome/brands/github
  palette: 


    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: deep orange
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 亮色模式

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: 暗色模式

extra:
  generator: false
  social:
    - icon: fontawesome/brands/pied-piper-alt
      link: http://home.liheng.work/
    - icon: fontawesome/brands/github
      link: https://github.com/lmliheng?tab=repositories

repo_url: https://github.com/lmliheng/codes
repo_name: Heng's Codes

copyright: Copyright 2024 Write By Heng 

markdown_extensions:
  - pymdownx.highlight:

      anchor_linenums: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences  