site_name: windows
site_author: HENG
site_url: 
use_directory_urls: false
nav:
     - 主页: index.md
     - 磁盘分区: disk.md
     - 快捷方式和快捷键: shortcut.md
     - 网络管理: network.md
     - 服务管理: server.md
     - 应用管理: app.md
     - 系统管理: system.md
     - winows API: api.md
     - 环境变量管理: env.md

theme: 
  name: material
  language: zh
  palette:
    scheme: default
    primary: deep orange
  features:
    - content.code.copy
    - content.code.select
  icon:
    repo: fontawesome/brands/github
  palette: 


    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: deep orange
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 亮色模式

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: 暗色模式

extra:
  generator: false
  social:
    - icon: fontawesome/brands/pied-piper-alt
      link: http://home.liheng.work/
    - icon: fontawesome/brands/github
      link: https://github.com/lmliheng?tab=repositories

repo_url: https://github.com/lmliheng/codes
repo_name: Heng's Codes

copyright: Copyright 2024 Write By Heng 

markdown_extensions:
  - pymdownx.highlight:

      anchor_linenums: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences  