site_name: Vue
site_author: HENG
site_url: 
use_directory_urls: false
nav:
     - 主页: index.md
     - 构建: build.md
     - 开发: dev.md
     - 部署: deploy.md
     - 规范: rule.md
     - 常见问题: question.md


theme: material